name: Build macOS ARM64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          sw_vers
          uname -m
          sysctl machdep.cpu.brand_string
